<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Audrey Lee" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<p>This dataset explores the energy produced by each US state in the year 2009. The energy produced is described by biomass, geothermal, solar, wind, hydro, HPS, coal, petroleum, gas, nuclear, and other. The states are separated into regions. This dataset was extremely robust, but I was interested in seeing the relationship between region of the US and the type of energy produced. The regions for this dataset are Alaska, California, Florida, Hawaii, Heartland, Mid Atlantic, Midwest, New England, New York, Southeast, Texas, and West. During the climate crisis, it is important to look to our shortcomings and our strengths. I aim to have a career in sustainable energy law, so it appealed to me to find a relationship between different types of energy production and their location in the US.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(readxl)
Project2RawData &lt;- read_xlsx(&quot;Project2RawData.xlsx&quot;)

glimpse(data)</code></pre>
<pre><code>## function (..., list = character(), package = NULL,
lib.loc = NULL, verbose = getOption(&quot;verbose&quot;),
## envir = .GlobalEnv, overwrite = TRUE)</code></pre>
<pre class="r"><code>library(mvtnorm)
library(ggExtra)

glimpse(Project2RawData)</code></pre>
<pre><code>## Rows: 51
## Columns: 14
## $ State &lt;chr&gt; &quot;Alabama&quot;, &quot;Alaska&quot;, &quot;Arizona&quot;,
&quot;Arkansas&quot;, &quot;California&quot;, &quot;Colorado&quot;, &quot;Conne…
## $ Abbreviation &lt;chr&gt; &quot;AL&quot;, &quot;AK&quot;, &quot;AZ&quot;, &quot;AR&quot;, &quot;CA&quot;, &quot;CO&quot;,
&quot;CT&quot;, &quot;DE&quot;, &quot;DC&quot;, &quot;FL&quot;, &quot;GA&quot;, &quot;HI&quot;, &quot;ID&quot;…
## $ Region &lt;chr&gt; &quot;Southeast&quot;, &quot;Alaska&quot;, &quot;West&quot;,
&quot;Southeast&quot;, &quot;California&quot;, &quot;West&quot;, &quot;New Engla…
## $ Biomass &lt;dbl&gt; 0.000, 0.000, 3291195.898, 4254.745,
159645.589, 1478309.688, 6062630.318, 5…
## $ Geothermal &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
13022835.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1675…
## $ Solar &lt;dbl&gt; 0.000, 0.000, 0.000, 0.000, 13759.445,
0.000, 611763.387, 16530.477, 0.000, …
## $ Wind &lt;dbl&gt; 0.000, 0.000, 0.000, 3062.442, 9555.000,
0.000, 5764637.309, 2942132.635, 0.…
## $ Hydro &lt;dbl&gt; 0.00, 0.00, 11753493.37, 1204550.39,
6348462.99, 4195168.35, 27707085.47, 20…
## $ HPS &lt;dbl&gt; 0, 0, 0, 0, 169480, 100365, 144453, -108658,
5385, 0, 0, 0, 271988, 0, 0, 0,…
## $ Coal &lt;dbl&gt; 0.00, 0.00, 55659872.11, 566821.97,
39783825.82, 25075250.30, 1948279.09, 31…
## $ Petroleum &lt;dbl&gt; 0.000, 0.000, 163054.219, 1191884.181,
67337.470, 87673.592, 1638018.869, 15…
## $ Gas &lt;dbl&gt; 0.00, 0.00, 32369862.92, 3571100.82,
34852149.55, 11368417.10, 115749546.20,…
## $ Nuclear &lt;dbl&gt; 0, 0, 39716204, 0, 30661851, 15169966,
31734676, 0, 16657387, 0, 0, 29336059…
## $ Other &lt;dbl&gt; 0.000, 0.000, 7136.532, 0.000, 533.921,
24018.741, 440323.360, 33632.811, 71…</code></pre>
<pre class="r"><code>library(mvtnorm); library(ggExtra)
df&lt;-rmvnorm(1000,mean=c(0,0),sigma=matrix(c(1,.5,.5,1),ncol=2,byrow=T))
df&lt;-data.frame(df)%&gt;%rename(Y1=X1,Y2=X2)
p&lt;-ggplot(df, aes(Y1,Y2))+geom_point(alpha=.5)+geom_density_2d(h=2)+coord_fixed()
ggMarginal(p,type=&quot;density&quot;,xparams = list(bw=.5), yparams=list(bw=.5))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-1-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>p</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-1-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(Project2RawData,aes(x=Petroleum,y=Gas))+geom_point(alpha=.5)+geom_density_2d(h=2)+coord_fixed()+facet_wrap(~Region)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-1-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(rstatix)
group&lt;-Project2RawData$Region
DVs&lt;-Project2RawData%&gt;%select(Biomass,Geothermal,Solar,Wind,Hydro,HPS,Coal,Petroleum,Gas,Nuclear,Other)
man1&lt;-manova(cbind(Biomass,Geothermal,Solar,Wind,Hydro,HPS,Coal,Petroleum,Gas,Nuclear,Other)~Region,data=Project2RawData)
summary(man1)</code></pre>
<pre><code>##           Df Pillai approx F num Df den Df Pr(&gt;F)
## Region    11 2.4115  0.99549    121    429 0.5015
## Residuals 39</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response Biomass :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 2.3041e+13 2.0947e+12 1.3496 0.2354
## Residuals 39 6.0529e+13 1.5520e+12
##
## Response Geothermal :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 2.4211e+13 2.2010e+12 0.5978 0.8188
## Residuals 39 1.4359e+14 3.6818e+12
##
## Response Solar :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 5.2756e+10 4795971016 0.5633 0.8461
## Residuals 39 3.3203e+11 8513707579
##
## Response Wind :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 1.0579e+14 9.6175e+12 1.0351 0.4358
## Residuals 39 3.6238e+14 9.2917e+12
##
## Response Hydro :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 1.3752e+15 1.2502e+14 0.824 0.6172
## Residuals 39 5.9169e+15 1.5172e+14
##
## Response HPS :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 4.9224e+11 4.4749e+10 0.4285 0.9338
## Residuals 39 4.0730e+12 1.0444e+11
##
## Response Coal :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 8.8662e+15 8.0602e+14 0.5982 0.8185
## Residuals 39 5.2551e+16 1.3475e+15
##
## Response Petroleum :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 7.6076e+13 6.9160e+12 3.7551 0.001045 **
## Residuals 39 7.1830e+13 1.8418e+12
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Gas :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 2.2158e+16 2.0143e+15 2.1028 0.04368 *
## Residuals 39 3.7360e+16 9.5794e+14
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Nuclear :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 2.9361e+15 2.6692e+14 0.5694 0.8415
## Residuals 39 1.8282e+16 4.6878e+14
##
## Response Other :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Region 11 6.2994e+12 5.7267e+11 8.6247 1.834e-07 ***
## Residuals 39 2.5896e+12 6.6399e+10
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>Project2RawData%&gt;%group_by(Region)%&gt;%summarize(mean(Biomass),mean(Geothermal),mean(Solar),mean(Wind),mean(Hydro),mean(HPS),mean(Coal),mean(Petroleum),mean(Gas),mean(Nuclear),mean(Other))</code></pre>
<pre><code>## # A tibble: 12 x 12
## Region `mean(Biomass)` `mean(Geotherma… `mean(Solar)`
`mean(Wind)` `mean(Hydro)` `mean(HPS)`
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Alaska 0 0 0 0 0 0
## 2 Calif… 159646.  0 13759.  9555 6348463.  169480
## 3 Flori… 138302.  0 0 0 0 0
## 4 Hawaii 4237764.  0 10225 0 244526.  0
## 5 Heart… 135941.  0 0 2079740.  997756.  0
## 6 Mid A… 877858.  217047.  16974.  571847.  2675851.
-139265.
## 7 Midwe… 897136.  0 9.62 1294472.  15365322.  -56418.
## 8 New E… 2045800.  2170473.  101961.  4842160.
11711597.  24076.
## 9 New Y… 914529.  0 2438.  19150.  37117.  0
## 10 South… 786730.  0 0 1743059.  919449.  -239365.
## 11 Texas 5775.  0 0 392308.  4319205.  0
## 12 West 1215725.  0 0 166053.  4294727.  -27748.
## # … with 5 more variables: `mean(Coal)` &lt;dbl&gt;,
`mean(Petroleum)` &lt;dbl&gt;, `mean(Gas)` &lt;dbl&gt;,
## # `mean(Nuclear)` &lt;dbl&gt;, `mean(Other)` &lt;dbl&gt;</code></pre>
<p>The null hypothesis for a MANOVA test states that for each numeric response variable, the mean of all groups (regions of the US) are equal. The alternate hypothesis states that for at least 1 measure of energy produced, at least 1 region mean differs. This test is appropriate when we have multiple response variables (ie multiple types of energy produced in a year) to see if any differ by the categorical explanatory variable of US region. The assumptions for MANOVA are extensive. Random sampling, independent observations, multivariate normality of DVs, homogeneity of within group covariance matrices, linear relationships among DVs, no extreme univariate or multivariate outliers, and no mukticollinearity are required. This is a lot of assumptions, and it’s unlikely that all of them are met in this case. Again, the regions for this dataset are Alaska, California, Florida, Hawaii, Heartland, Mid Atlantic, Midwest, New England, New York, Southeast, Texas, and West. I decided to focus on 6 numeric variables: wind, hydro, petroleum, solar, coal, and gas.</p>
<p>The overeall manova test was not significant. I was shocked by this! If everything had been significant, I would have had 11 response variables for 12 groups. That would mean 1 MANOVA, 11 ANOVA, and 12 t-tests, or 24 tests total. I included the code for the first steps to be safe.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>Project2RawData&lt;-na.omit(Project2RawData)
Project2RawData$Biomass%&gt;%sort</code></pre>
<pre><code>## [1] 0.000 0.000 0.000 0.000 0.000 890.379 4254.745
5774.833
## [9] 8453.340 17433.377 29266.424 50527.669 56857.101
60163.014 100425.453 138301.819
## [17] 152776.313 159645.589 175257.730 192385.379
263427.996 294673.699 373142.927 380464.045
## [25] 477948.276 539982.458 599703.453 751004.489
752801.224 753801.138 896430.522 914529.032
## [33] 1089622.843 1259418.764 1382742.694 1397117.988
1437051.358 1478309.688 1543616.996 1733560.686
## [41] 2019958.579 2081064.256 2143017.095 2250155.244
2465738.035 2493390.121 2931302.106 3291195.898
## [49] 3637794.872 4237764.241 6062630.318</code></pre>
<pre class="r"><code>mean(Project2RawData$Biomass)</code></pre>
<pre><code>## [1] 1040898</code></pre>
<pre class="r"><code>samp1&lt;-sample(Project2RawData$Biomass,replace=T)
sort(samp1)</code></pre>
<pre><code>## [1] 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
## [9] 890.379 4254.745 4254.745 4254.745 5774.833
17433.377 17433.377 17433.377
## [17] 17433.377 17433.377 29266.424 29266.424 56857.101
60163.014 60163.014 60163.014
## [25] 100425.453 100425.453 138301.819 138301.819
138301.819 159645.589 263427.996 380464.045
## [33] 380464.045 477948.276 477948.276 599703.453
751004.489 1089622.843 1259418.764 1259418.764
## [41] 1397117.988 1437051.358 1733560.686 2143017.095
2250155.244 2493390.121 2493390.121 2931302.106
## [49] 2931302.106 3291195.898 3637794.872</code></pre>
<pre class="r"><code>samp1</code></pre>
<pre><code>## [1] 4254.745 3291195.898 5774.833 29266.424 751004.489
17433.377 1733560.686 599703.453
## [9] 0.000 477948.276 3637794.872 60163.014 2493390.121
0.000 0.000 56857.101
## [17] 0.000 477948.276 17433.377 100425.453 138301.819
138301.819 1089622.843 380464.045
## [25] 2250155.244 17433.377 380464.045 1437051.358
138301.819 159645.589 4254.745 0.000
## [33] 100425.453 2143017.095 0.000 1397117.988 890.379
29266.424 17433.377 0.000
## [41] 2931302.106 60163.014 2931302.106 1259418.764
1259418.764 263427.996 0.000 2493390.121
## [49] 60163.014 17433.377 4254.745</code></pre>
<pre class="r"><code>mean(samp1)</code></pre>
<pre><code>## [1] 683462.3</code></pre>
<pre class="r"><code>means&lt;-vector()
for(i in 1:5000){
samp&lt;-sample(Project2RawData$Biomass,replace=T)
means[i]&lt;-mean(samp)
}
quantile(means,c(0.025,0.975),na.rm=TRUE)</code></pre>
<pre><code>##      2.5%     97.5% 
##  708929.5 1395109.6</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(means))+geom_vline(xintercept=quantile(means,c(.025,.975)))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>sd(means)</code></pre>
<pre><code>## [1] 175697.3</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(means))+
  geom_vline(xintercept=mean(means)+c(-1,1)*sd(means))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(vegan)
dists&lt;-Project2RawData%&gt;%select(Biomass, Wind)%&gt;%dist()
adonis(dists~Region,data=Project2RawData)</code></pre>
<pre><code>## 
## Call:
## adonis(formula = dists ~ Region, data = Project2RawData) 
## 
## Permutation: free
## Number of permutations: 999
## 
## Terms added sequentially (first to last)
## 
##           Df  SumsOfSqs    MeanSqs F.Model     R2 Pr(&gt;F)
## Region    11 1.2883e+14 1.1712e+13  1.0801 0.2335  0.243
## Residuals 39 4.2291e+14 1.0844e+13         0.7665       
## Total     50 5.5174e+14                    1.0000</code></pre>
<p>The null hypothesis is that the true mean of biomass generated in the US by state does not differ from the mean of the biomass generated in this dataset from 2009. The alternate hypothesis is that the true mean of biomass does differ significantly from the mean in this dataset. The histogram above shows a normal distribution with the quantiles included. Our mean falls within the range of sd. We can conclude that it is representative of the true mean of biomass, so we fail to reject the null.</p>
<ul>
<li><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</li>
</ul>
<pre class="r"><code>Project2RawData%&gt;%ggplot(aes(Nuclear,Coal))+geom_point()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit&lt;-lm(Nuclear~Coal+Gas,data=Project2RawData);summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Nuclear ~ Coal + Gas, data =
Project2RawData)
##
## Residuals:
## Min 1Q Median 3Q Max
## -32104668 -9196531 -4756790 5235508 66357036
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.069e+06 3.525e+06 1.438 0.1569
## Coal 2.427e-01 7.638e-02 3.178 0.0026 **
## Gas 1.263e-01 7.759e-02 1.627 0.1102
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 17960000 on 48 degrees of
freedom
## Multiple R-squared: 0.2704, Adjusted R-squared: 0.24
## F-statistic: 8.894 on 2 and 48 DF, p-value: 0.0005179</code></pre>
<pre class="r"><code>resCoal&lt;-lm(Nuclear~Gas,data=Project2RawData)$residuals
resGas&lt;-lm(Nuclear~Coal,data=Project2RawData)$residuals
coef(lm(resCoal~resGas))</code></pre>
<pre><code>##  (Intercept)       resGas 
## 1.043290e-09 9.154622e-01</code></pre>
<pre class="r"><code>coef(lm(Nuclear~Coal+Gas,data=Project2RawData))</code></pre>
<pre><code>##  (Intercept)         Coal          Gas 
## 5.068932e+06 2.427016e-01 1.262576e-01</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Nuclear ~ Coal + Gas, data =
Project2RawData)
##
## Residuals:
## Min 1Q Median 3Q Max
## -32104668 -9196531 -4756790 5235508 66357036
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.069e+06 3.525e+06 1.438 0.1569
## Coal 2.427e-01 7.638e-02 3.178 0.0026 **
## Gas 1.263e-01 7.759e-02 1.627 0.1102
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 17960000 on 48 degrees of
freedom
## Multiple R-squared: 0.2704, Adjusted R-squared: 0.24
## F-statistic: 8.894 on 2 and 48 DF, p-value: 0.0005179</code></pre>
<pre class="r"><code>Nuclear&lt;-Project2RawData$Nuclear
(sum((Nuclear-mean(Nuclear))^2)-sum(fit$residuals^2))/sum(Nuclear-mean(Nuclear)^2)</code></pre>
<pre><code>## [1] -0.4759429</code></pre>
<pre class="r"><code>library(sandwich);library(lmtest)
fit&lt;-lm(Nuclear~Coal+Gas,data=Project2RawData)
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 12.003, df = 2, p-value = 0.002475</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                 Estimate   Std. Error
## (Intercept) 5.068932e+06 3.524787e+06
## Coal        2.427016e-01 7.637794e-02
## Gas         1.262576e-01 7.758774e-02</code></pre>
<pre class="r"><code>coeftest(fit,vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                 Estimate   Std. Error
## (Intercept) 5.068932e+06 3.699577e+06
## Coal        2.427016e-01 1.368216e-01
## Gas         1.262576e-01 1.495188e-01</code></pre>
<pre class="r"><code>fit&lt;-lm(Nuclear~Coal*Gas,data=Project2RawData)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Nuclear ~ Coal * Gas, data =
Project2RawData)
##
## Residuals:
## Min 1Q Median 3Q Max
## -35621925 -8226005 -2348883 4577761 63756770
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.860e+06 3.948e+06 0.471 0.639752
## Coal 3.076e-01 8.426e-02 3.651 0.000655 ***
## Gas 3.012e-01 1.287e-01 2.341 0.023541 *
## Coal:Gas -2.165e-09 1.284e-09 -1.686 0.098335 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 17620000 on 47 degrees of
freedom
## Multiple R-squared: 0.312, Adjusted R-squared: 0.2681
## F-statistic: 7.105 on 3 and 47 DF, p-value: 0.0004936</code></pre>
<pre class="r"><code>Project2RawData$Coal_c&lt;-Project2RawData$Coal-mean(Project2RawData$Coal)
Project2RawData$Gas_c&lt;-Project2RawData$Gas-mean(Project2RawData$Gas)
fit&lt;-lm(Nuclear~Coal_c*Gas_c,data=Project2RawData)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Nuclear ~ Coal_c * Gas_c, data =
Project2RawData)
##
## Residuals:
## Min 1Q Median 3Q Max
## -35621925 -8226005 -2348883 4577761 63756770
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.618e+07 2.514e+06 6.437 5.85e-08 ***
## Coal_c 2.684e-01 7.648e-02 3.509 0.0010 **
## Gas_c 2.297e-01 9.778e-02 2.349 0.0231 *
## Coal_c:Gas_c -2.165e-09 1.284e-09 -1.686 0.0983 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 17620000 on 47 degrees of
freedom
## Multiple R-squared: 0.312, Adjusted R-squared: 0.2681
## F-statistic: 7.105 on 3 and 47 DF, p-value: 0.0004936</code></pre>
<pre class="r"><code>resids&lt;-fit$residuals;fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 15.903, df = 3, p-value = 0.001187</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids),bins=20)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" />
I first ran the model in a simple linear model without interactions to get a general idea of how the data looked. 5.069x10^6 is the predicted value of nuclear energy production when coal and gas are 0. 2.43x10^-1 is the slope for coal on nuclear when holding gas constant. 1.26x10^-1 is the slope of gas on nuclear when holding coal constant. This linear model returned a massive residual standard error of 17960000 on 48 df. I could tell from an initial ggplot that heteroskedasticity was violated. I wanted to check, so I went ahead and did a Breusch-Pagan test, and adjusted.</p>
<p>I reran the model to account for interactions and mean center, as well as violations of assumptions. With interactions, 1.86x10^6 is the predicted value of nuclear energy production when coal and gas are 0. 0.308 is the slope for coal on nuclear when holding gas constant. 0.3012 is the slope of gas on nuclear when holding coal constant. After plotting the residuals, it was clear that homoskedasticity was violated. There were also many outliers that made it clear normality was violated as well. However, the bp test returned a p-value of 0.001187.</p>
<pre><code>- Interpret the coefficient estimates (do not discuss significance) (10)
- Plot the regression using `ggplot()` using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the `interactions` package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)
- What proportion of the variation in the outcome does your model explain? (4)
- Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)
- Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</code></pre>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-boot_dat&lt;-Project2RawData[sample(nrow(Project2RawData),replace=TRUE),]
  fit&lt;-lm(Nuclear ~ Coal_c * Gas_c, data=boot_dat)
  coef(fit)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)    Coal_c     Gas_c Coal_c:Gas_c
## 1     2937134 0.1295303 0.1631996 5.733076e-09</code></pre>
<pre class="r"><code>samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% pivot_longer(1:3) %&gt;% group_by(name) %&gt;%
summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   name                lower        upper
##   &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;
## 1 (Intercept) 11368938.     22688439.   
## 2 Coal_c             0.0478        0.548
## 3 Gas_c              0.0950        0.754</code></pre>
<pre class="r"><code>fit&lt;-lm(Nuclear~Coal_c*Gas_c,data=Project2RawData)
resids&lt;-fit$residuals
fitted&lt;-fit$fitted.values
resid_resamp&lt;-replicate(5000,{
    new_resids&lt;-sample(resids,replace=TRUE)
    Project2RawData$new_y&lt;-fitted+new_resids 
    fit&lt;-lm(Nuclear~Coal_c*Gas_c,data=Project2RawData)
    coef(fit)
})

resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) Coal_c Gas_c Coal_c:Gas_c
## 1           0      0     0            0</code></pre>
<pre class="r"><code>resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%pivot_longer(1:3)%&gt;%group_by(name)%&gt;%
 summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   name               lower        upper
##   &lt;chr&gt;              &lt;dbl&gt;        &lt;dbl&gt;
## 1 (Intercept) 16184881.    16184881.   
## 2 Coal_c             0.268        0.268
## 3 Gas_c              0.230        0.230</code></pre>
<p>The bootstrapped values returned a big increase in the intercept and coal and gas values compared to the robust values.</p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>data&lt;-Project2RawData%&gt;%mutate(y=ifelse(Region==&quot;Texas&quot;,1,0))
head(data)</code></pre>
<pre><code>## # A tibble: 6 x 17
## State Abbreviation Region Biomass Geothermal Solar Wind
Hydro HPS Coal Petroleum Gas
## &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
&lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Alab… AL South… 0.  0 0 0 0.  0 0.  0 0.
## 2 Alas… AK Alaska 0.  0 0 0 0.  0 0.  0 0.
## 3 Ariz… AZ West 3.29e6 0 0 0 1.18e7 0 5.57e7 163054.
3.24e7
## 4 Arka… AR South… 4.25e3 0 0 3062. 1.20e6 0 5.67e5
1191884. 3.57e6
## 5 Cali… CA Calif… 1.60e5 0 13759. 9555 6.35e6 169480
3.98e7 67337. 3.49e7
## 6 Colo… CO West 1.48e6 0 0 0 4.20e6 100365 2.51e7 87674.
1.14e7
## # … with 5 more variables: Nuclear &lt;dbl&gt;, Other &lt;dbl&gt;,
Coal_c &lt;dbl&gt;, Gas_c &lt;dbl&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>odds&lt;-function(p)p/(1-p)
p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>head(data)</code></pre>
<pre><code>## # A tibble: 6 x 17
## State Abbreviation Region Biomass Geothermal Solar Wind
Hydro HPS Coal Petroleum Gas
## &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
&lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Alab… AL South… 0.  0 0 0 0.  0 0.  0 0.
## 2 Alas… AK Alaska 0.  0 0 0 0.  0 0.  0 0.
## 3 Ariz… AZ West 3.29e6 0 0 0 1.18e7 0 5.57e7 163054.
3.24e7
## 4 Arka… AR South… 4.25e3 0 0 3062. 1.20e6 0 5.67e5
1191884. 3.57e6
## 5 Cali… CA Calif… 1.60e5 0 13759. 9555 6.35e6 169480
3.98e7 67337. 3.49e7
## 6 Colo… CO West 1.48e6 0 0 0 4.20e6 100365 2.51e7 87674.
1.14e7
## # … with 5 more variables: Nuclear &lt;dbl&gt;, Other &lt;dbl&gt;,
Coal_c &lt;dbl&gt;, Gas_c &lt;dbl&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>fit&lt;-glm(y~Petroleum+Gas,data=data,family=binomial(link=&quot;logit&quot;))
fit</code></pre>
<pre><code>##
## Call: glm(formula = y ~ Petroleum + Gas, family =
binomial(link = &quot;logit&quot;),
## data = data)
##
## Coefficients:
## (Intercept) Petroleum Gas
## -1.344e+00 -3.189e-05 -1.133e-06
##
## Degrees of Freedom: 50 Total (i.e. Null); 48 Residual
## Null Deviance: 9.844
## Residual Deviance: 5.787 AIC: 11.79</code></pre>
<pre class="r"><code>coeftest(fit)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.3436e+00  1.3309e+00 -1.0095   0.3127
## Petroleum   -3.1887e-05  6.2869e-05 -0.5072   0.6120
## Gas         -1.1335e-06  2.8788e-06 -0.3937   0.6938</code></pre>
<pre class="r"><code>exp(coef(fit))</code></pre>
<pre><code>## (Intercept)   Petroleum         Gas 
##   0.2609101   0.9999681   0.9999989</code></pre>
<pre class="r"><code>exp(-4.96E15)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>logistic&lt;-function(x){exp(x)/(1+exp(x))}
ggplot()+geom_function(fun=logistic)+xlab(&quot;t&quot;)+ylab(&quot;p(y=1)&quot;)+xlim(-10,10)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>data&lt;-data%&gt;%mutate(petro_cat=ntile(Petroleum,3))
data$petro_cat&lt;-factor(data$petro_cat,labels=c(&quot;S&quot;,&quot;M&quot;,&quot;L&quot;))
fit1&lt;-glm(y~petro_cat,data=data,family=binomial(link=&quot;logit&quot;))
summary(fit1)</code></pre>
<pre><code>##
## Call:
## glm(formula = y ~ petro_cat, family = binomial(link =
&quot;logit&quot;),
## data = data)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -0.34821 -0.34821 -0.00003 -0.00003 2.38043
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -2.773 1.031 -2.690 0.00715 **
## petro_catM -18.793 7089.908 -0.003 0.99789
## petro_catL -18.793 7089.908 -0.003 0.99789
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 9.8439 on 50 degrees of freedom
## Residual deviance: 7.6064 on 48 degrees of freedom
## AIC: 13.606
##
## Number of Fisher Scoring iterations: 20</code></pre>
<pre class="r"><code>exp(-18.793)</code></pre>
<pre><code>## [1] 6.891342e-09</code></pre>
<pre class="r"><code>exp(-18.793)</code></pre>
<pre><code>## [1] 6.891342e-09</code></pre>
<pre class="r"><code>info&lt;-table(truth=data$y,prediction=data$petro_cat)%&gt;%addmargins
info</code></pre>
<pre><code>##      prediction
## truth  S  M  L Sum
##   0   16 17 17  50
##   1    1  0  0   1
##   Sum 17 17 17  51</code></pre>
<pre class="r"><code>(16)/51</code></pre>
<pre><code>## [1] 0.3137255</code></pre>
<pre class="r"><code>(17)/50</code></pre>
<pre><code>## [1] 0.34</code></pre>
<pre class="r"><code>(16/17)</code></pre>
<pre><code>## [1] 0.9411765</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>##  (Intercept)   petro_catM   petro_catL 
## 6.250000e-02 6.888036e-09 6.888036e-09</code></pre>
<pre class="r"><code>coef(fit1)%&gt;%round(5)%&gt;%data.frame</code></pre>
<pre><code>##                     .
## (Intercept)  -2.77259
## petro_catM  -18.79348
## petro_catL  -18.79348</code></pre>
<pre class="r"><code>exp(-2.773)</code></pre>
<pre><code>## [1] 0.0624743</code></pre>
<pre class="r"><code>odds2prob&lt;-function(odds){odds/(1+odds)}
odds2prob(0.06247)</code></pre>
<pre><code>## [1] 0.05879695</code></pre>
<pre class="r"><code>exp(-1.879)</code></pre>
<pre><code>## [1] 0.1527428</code></pre>
<pre class="r"><code>probs&lt;-predict(fit1,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;0.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   50  1  51
##     Sum 50  1  51</code></pre>
<pre class="r"><code>hist(table(predict=as.numeric(probs&gt;0.5),truth=data$y)%&gt;%addmargins
)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>model.df=augment(fit1)%&gt;%rename(log_odds=&#39;.fitted&#39;,)
glimpse(model.df)</code></pre>
<pre><code>## Rows: 51
## Columns: 8
## $ y &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ petro_cat &lt;fct&gt; S, S, M, L, M, M, L, S, M, M, S, L, L,
L, S, M, M, M, M, L, L, L, M, L, L, M, …
## $ log_odds &lt;dbl&gt; -2.772589, -2.772589, -21.566069,
-21.566069, -21.566069, -21.566069, -21.5660…
## $ .resid &lt;dbl&gt; -3.482086e-01, -3.482086e-01,
-2.934288e-05, -2.934288e-05, -2.934288e-05, -2.…
## $ .std.resid &lt;dbl&gt; -3.589252e-01, -3.589252e-01,
-3.024595e-05, -3.024595e-05, -3.024595e-05, -3.…
## $ .hat &lt;dbl&gt; 0.05882353, 0.05882353, 0.05882353,
0.05882353, 0.05882353, 0.05882353, 0.0588…
## $ .sigma &lt;dbl&gt; 0.3988704, 0.3988704, 0.4022917,
0.4022917, 0.4022917, 0.4022917, 0.4022917, 0…
## $ .cooksd &lt;dbl&gt; 1.383464e-03, 1.383464e-03,
9.529347e-12, 9.529347e-12, 9.529347e-12, 9.529347…</code></pre>
<pre class="r"><code>ggplot(model.df,aes(y,log_odds,colour=y))+geom_line()+geom_smooth(se=TRUE)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>model.df</code></pre>
<pre><code>## # A tibble: 51 x 8
## y petro_cat log_odds .resid .std.resid .hat .sigma
.cooksd
## &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 0 S -2.77 -0.348 -0.359 0.0588 0.399 1.38e- 3
## 2 0 S -2.77 -0.348 -0.359 0.0588 0.399 1.38e- 3
## 3 0 M -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 4 0 L -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 5 0 M -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 6 0 M -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 7 0 L -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 8 0 S -2.77 -0.348 -0.359 0.0588 0.399 1.38e- 3
## 9 0 M -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## 10 0 M -21.6 -0.0000293 -0.0000302 0.0588 0.402 9.53e-12
## # … with 41 more rows</code></pre>
<pre class="r"><code>ggplot(model.df, aes(x=log_odds , y=model.df$y )) +
  geom_point()  +  stat_smooth(method=&quot;glm&quot;, se=FALSE, method.args = list(family=binomial)) +  facet_wrap( ~ petro_cat)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(data[data$y==1,]$prob&gt;.1)</code></pre>
<pre><code>## [1] NaN</code></pre>
<pre class="r"><code>mean(data[data$y==1,]$prob&lt;.1)</code></pre>
<pre><code>## [1] NaN</code></pre>
<pre class="r"><code>logit&lt;-glm(y~petro_cat,data=data,family=binomial(link=&quot;logit&quot;))
logit</code></pre>
<pre><code>##
## Call: glm(formula = y ~ petro_cat, family =
binomial(link = &quot;logit&quot;),
## data = data)
##
## Coefficients:
## (Intercept) petro_catM petro_catL
## -2.773 -18.793 -18.793
##
## Degrees of Freedom: 50 Total (i.e. Null); 48 Residual
## Null Deviance: 9.844
## Residual Deviance: 7.606 AIC: 13.61</code></pre>
<pre class="r"><code>exp(coef(fit))</code></pre>
<pre><code>## (Intercept)   Petroleum         Gas 
##   0.2609101   0.9999681   0.9999989</code></pre>
<pre class="r"><code>exp(cbind(coef(fit),confint(fit)))</code></pre>
<pre><code>##                             2.5 %    97.5 %
## (Intercept) 0.2609101 0.009672107 2.7885066
## Petroleum   0.9999681 0.999711551 1.0000073
## Gas         0.9999989          NA 0.9999995</code></pre>
<p>Petroleum energy production increases the log odds of the region being Texas. For petroleum = 0, the log odds is -4.96x10^15, odds of region being Texas is e<sup>-4.96x10</sup>15, or ~0. For petroleum production = 1, the log odds is -4.96x10^15 + 5.237x10^8, or still roughly 0. Every one unit increase in petroleum energy production (note that 1 unit is incredibly small when dealing with this kind of variable) causes odds to multiply by 1424379. I reran this model dividing petroleum into 3 categorial levels. The model was more successful this way. Odds of region being Texas for M are 6.89x10^9 times that of S. Odds of region being Texas for M are 6.89x10^9 times that of M.</p>
<p>Accuracy of the second model was 0.314. Specificity was 1.0. Sensitivity was 0.34. Precision was 0.941. The logit score was 0.1527.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>fit3&lt;-glm(y~Biomass+Geothermal+Solar+Wind+Hydro+HPS+Coal+Petroleum+Gas+Other,data=data,family=&quot;binomial&quot;)
coeftest(fit3)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.9095e+01  5.9620e+03 -0.0032   0.9974
## Biomass     -3.5143e-04  1.0484e-01 -0.0034   0.9973
## Geothermal   1.2420e-04  1.8901e-01  0.0007   0.9995
## Solar       -9.8758e-04  2.0338e+00 -0.0005   0.9996
## Wind         2.2767e-05  1.2347e-02  0.0018   0.9985
## Hydro        6.2786e-06  1.6816e-03  0.0037   0.9970
## HPS         -4.5733e-04  2.3106e-01 -0.0020   0.9984
## Coal        -2.7282e-06  1.7252e-03 -0.0016   0.9987
## Petroleum   -9.8639e-05  5.2148e-02 -0.0019   0.9985
## Gas         -1.8842e-06  3.4884e-03 -0.0005   0.9996
## Other        4.3902e-04  1.2948e-01  0.0034   0.9973</code></pre>
<pre class="r"><code>prob3&lt;-predict(fit3,type=&quot;response&quot;)
pred&lt;-ifelse(prob3&gt;.5,1,0)

exp(coef(fit3))%&gt;%round(3)%&gt;%t</code></pre>
<pre><code>## (Intercept) Biomass Geothermal Solar Wind Hydro HPS Coal
Petroleum Gas Other
## [1,] 0 1 1 0.999 1 1 1 1 1 1 1</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
 tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)
   if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
    ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,f1,auc)
}
finaldat&lt;-data%&gt;%select(-State,-Abbreviation,-Region,-petro_cat)
head(finaldat)</code></pre>
<pre><code>## # A tibble: 6 x 14
## Biomass Geothermal Solar Wind Hydro HPS Coal Petroleum
Gas Nuclear Other Coal_c
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
&lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 0.  0 0 0 0.  0 0.  0 0.  0.  0 -3.30e7
## 2 0.  0 0 0 0.  0 0.  0 0.  0.  0 -3.30e7
## 3 3.29e6 0 0 0 1.18e7 0 5.57e7 163054. 3.24e7 3.97e7
7137.  2.26e7
## 4 4.25e3 0 0 3062. 1.20e6 0 5.67e5 1191884. 3.57e6 0.  0
-3.25e7
## 5 1.60e5 0 13759. 9555 6.35e6 169480 3.98e7 67337.
3.49e7 3.07e7 534.  6.76e6
## 6 1.48e6 0 0 0 4.20e6 100365 2.51e7 87674. 1.14e7 1.52e7
24019. -7.95e6
## # … with 2 more variables: Gas_c &lt;dbl&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>fit&lt;-glm(y~(.)^2,data=finaldat,family=&quot;binomial&quot;)
prob&lt;-predict(fit,type=&quot;response&quot;)
class_diag(prob,finaldat$y)</code></pre>
<pre><code>##   acc sens spec ppv f1 auc
## 1   1    1    1   1  1   1</code></pre>
<pre class="r"><code>set.seed(1234)
first_half&lt;-finaldat%&gt;%sample_frac(0.5)
second_half&lt;-anti_join(finaldat,first_half)
fit&lt;-glm(y~(.)^2,data=first_half,family=&quot;binomial&quot;)
probs1&lt;-predict(fit,newdata=second_half,type=&quot;response&quot;)
truth1&lt;-second_half$y
table(prediction=as.numeric(probs1&gt;.5),truth1)</code></pre>
<pre><code>##           truth1
## prediction  0
##          0 12
##          1 13</code></pre>
<pre class="r"><code>fit&lt;-glm(y~(.)^2,data=second_half,family=&quot;binomial&quot;)
probs2&lt;-predict(fit,newdata=first_half,type=&quot;response&quot;)
truth2&lt;-first_half$y
table(prediction=as.numeric(probs2&gt;.5),truth2)</code></pre>
<pre><code>##           truth2
## prediction  0  1
##          0 25  1</code></pre>
<pre class="r"><code>class_diag(probs2,truth2)</code></pre>
<pre><code>##         acc sens spec ppv  f1 auc
## 1 0.9615385    0    1 NaN NaN 0.6</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
donedat&lt;-finaldat%&gt;%sample_frac
donedat</code></pre>
<pre><code>## # A tibble: 51 x 14
## Biomass Geothermal Solar Wind Hydro HPS Coal Petroleum
Gas Nuclear Other Coal_c
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
&lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 5.69e4 0 0 4.99e5 1.91e6 566713 7.18e7 86777. 3.40e6
1.02e7 2.74e4 3.88e7
## 2 7.53e5 0 0 2.76e6 1.61e5 0 9.09e7 110882. 4.36e6
9.41e7 6.43e4 5.79e7
## 3 3.64e6 0 0 2.60e5 4.59e6 0 7.24e4 480670. 7.48e6 0.
3.52e5 -3.30e7
## 4 8.45e3 0 0 2.76e6 1.48e6 0 2.98e7 48076. 7.57e2 0.
8.38e2 -3.21e6
## 5 5.77e3 0 0 3.92e5 4.32e6 0 3.19e6 10089. 1.22e5 0.
3.13e4 -2.98e7
## 6 7.54e5 0 0 0.  6.23e5 5385 2.45e6 288349. 9.68e6
1.67e7 7.13e5 -3.06e7
## 7 1.60e5 0 13759. 9.56e3 6.35e6 169480 3.98e7 67337.
3.49e7 3.07e7 5.34e2 6.76e6
## 8 6.00e5 0 0 1.55e4 4.98e5 0 1.14e8 1311952. 4.75e6
1.49e7 1.44e4 8.08e7
## 9 1.44e6 0 0 3.54e6 7.39e7 52383 7.48e6 47275. 1.14e7
6.63e6 6.37e4 -2.55e7
## 10 4.25e3 0 0 3.06e3 1.20e6 0 5.67e5 1191884. 3.57e6 0.
0.  -3.25e7
## # … with 41 more rows, and 2 more variables: Gas_c
&lt;dbl&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>folds&lt;-ntile(1:nrow(finaldat),n=10)
probl&lt;-predict(fit,type=&quot;response&quot;)
class_diag(prob,donedat$y)</code></pre>
<pre><code>##         acc sens spec ppv  f1  auc
## 1 0.9607843    0 0.98   0 NaN 0.52</code></pre>
<pre class="r"><code>lastdat&lt;-donedat%&gt;%sample_frac
folds&lt;-ntile(1:nrow(data),n=10)
diags&lt;-NULL

library(glmnet)
y&lt;-as.matrix(data$y)
y</code></pre>
<pre><code>##       [,1]
##  [1,]    0
##  [2,]    0
##  [3,]    0
##  [4,]    0
##  [5,]    0
##  [6,]    0
##  [7,]    0
##  [8,]    0
##  [9,]    0
## [10,]    0
## [11,]    0
## [12,]    0
## [13,]    0
## [14,]    0
## [15,]    0
## [16,]    0
## [17,]    0
## [18,]    0
## [19,]    0
## [20,]    0
## [21,]    0
## [22,]    0
## [23,]    0
## [24,]    0
## [25,]    0
## [26,]    0
## [27,]    0
## [28,]    0
## [29,]    0
## [30,]    0
## [31,]    0
## [32,]    0
## [33,]    0
## [34,]    0
## [35,]    0
## [36,]    0
## [37,]    0
## [38,]    0
## [39,]    0
## [40,]    0
## [41,]    0
## [42,]    0
## [43,]    0
## [44,]    1
## [45,]    0
## [46,]    0
## [47,]    0
## [48,]    0
## [49,]    0
## [50,]    0
## [51,]    0</code></pre>
<pre class="r"><code>x&lt;-model.matrix(Region~.,data=data)[,-1]
head(x)</code></pre>
<pre><code>## StateAlaska StateArizona StateArkansas StateCalifornia
StateColorado StateConnecticut
## 1 0 0 0 0 0 0
## 2 1 0 0 0 0 0
## 3 0 1 0 0 0 0
## 4 0 0 1 0 0 0
## 5 0 0 0 1 0 0
## 6 0 0 0 0 1 0
## StateDelaware StateDistrict of Columbia StateFlorida
StateGeorgia StateHawaii StateIdaho
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## StateIllinois StateIndiana StateIowa StateKansas
StateKentucky StateLouisiana StateMaine
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## StateMaryland StateMassachusetts StateMichigan
StateMinnesota StateMississippi StateMissouri
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## StateMontana StateNebraska StateNevada StateNew
Hampshire StateNew Jersey StateNew Mexico
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## StateNew York StateNorth Carolina StateNorth Dakota
StateOhio StateOklahoma StateOregon
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## StatePennsylvania StateRhode Island StateSouth Carolina
StateSouth Dakota StateTennessee
## 1 0 0 0 0 0
## 2 0 0 0 0 0
## 3 0 0 0 0 0
## 4 0 0 0 0 0
## 5 0 0 0 0 0
## 6 0 0 0 0 0
## StateTexas StateUtah StateVermont StateVirginia
StateWashington StateWest Virginia StateWisconsin
## 1 0 0 0 0 0 0 0
## 2 0 0 0 0 0 0 0
## 3 0 0 0 0 0 0 0
## 4 0 0 0 0 0 0 0
## 5 0 0 0 0 0 0 0
## 6 0 0 0 0 0 0 0
## StateWyoming AbbreviationAL AbbreviationAR
AbbreviationAZ AbbreviationCA AbbreviationCO
## 1 0 1 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 1 0 0
## 4 0 0 1 0 0 0
## 5 0 0 0 0 1 0
## 6 0 0 0 0 0 1
## AbbreviationCT AbbreviationDC AbbreviationDE
AbbreviationFL AbbreviationGA AbbreviationHI
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationIA AbbreviationID AbbreviationIL
AbbreviationIN AbbreviationKS AbbreviationKY
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationLA AbbreviationMA AbbreviationMD
AbbreviationME AbbreviationMI AbbreviationMN
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationMO AbbreviationMS AbbreviationMT
AbbreviationNC AbbreviationND AbbreviationNE
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationNH AbbreviationNJ AbbreviationNM
AbbreviationNV AbbreviationNY AbbreviationOH
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationOK AbbreviationOR AbbreviationPA
AbbreviationRI AbbreviationSC AbbreviationSD
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationTN AbbreviationTX AbbreviationUT
AbbreviationVA AbbreviationVT AbbreviationWA
## 1 0 0 0 0 0 0
## 2 0 0 0 0 0 0
## 3 0 0 0 0 0 0
## 4 0 0 0 0 0 0
## 5 0 0 0 0 0 0
## 6 0 0 0 0 0 0
## AbbreviationWI AbbreviationWV AbbreviationWY Biomass
Geothermal Solar Wind Hydro
## 1 0 0 0 0.000 0 0.00 0.000 0
## 2 0 0 0 0.000 0 0.00 0.000 0
## 3 0 0 0 3291195.898 0 0.00 0.000 11753493
## 4 0 0 0 4254.745 0 0.00 3062.442 1204550
## 5 0 0 0 159645.589 0 13759.44 9555.000 6348463
## 6 0 0 0 1478309.688 0 0.00 0.000 4195168
## HPS Coal Petroleum Gas Nuclear Other Coal_c Gas_c y
petro_catM
## 1 0 0 0.00 0 0 0.000 -33027407 -18130807 0 0
## 2 0 0 0.00 0 0 0.000 -33027407 -18130807 0 0
## 3 0 55659872 163054.22 32369863 39716204 7136.532
22632465 14239055 0 1
## 4 0 566822 1191884.18 3571101 0 0.000 -32460585
-14559707 0 0
## 5 169480 39783826 67337.47 34852150 30661851 533.921
6756419 16721342 0 1
## 6 100365 25075250 87673.59 11368417 15169966 24018.741
-7952157 -6762390 0 1
## petro_catL
## 1 0
## 2 0
## 3 0
## 4 1
## 5 0
## 6 0</code></pre>
<pre class="r"><code>x&lt;-scale(x)</code></pre>
<p>The auc was quite high at 0.98, meaning that Texas region is being predicted fairly accurately. Acc and spec were quite high as well, while sense and ppv were low.</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>.
Run <code>install.packages("fivethirtyeight"),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
